import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import localFont from "next/font/local";
import theme from '../theme';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
  });
export default function RootLayout(props:any) {
  const { children } = props;
  return (
    <html lang="en">
     <body className={roboto.variable}>
         <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
             {children}
          </ThemeProvider>
         </AppRouterCacheProvider>
      </body>
    </html>
  );
}